name: Formatting
on: [push, pull_request]

jobs:
  formatting:
    runs-on: ubuntu-latest
    name: Code Formatting and Trailing Whitespace Check
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run Ruff for code formatting check
        uses: astral-sh/ruff-action@v1
        with:
          args: "format --check"

      - name: run yamlfmt
        uses: yk-lab/yamlfmt-action@v1
