name: Build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    name: Install
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
